--- 
- name: Apply cert-manager CIDRs
  shell: |
   kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.3/cert-manager.crds.yaml
   kubectl create namespace cert-manager
