---
- name: Revert K3s, Argo CD, and Longhorn Setup
  hosts: all
  become: true

  tasks:
    # Uninstall K3s
    - name: Uninstall K3s on all nodes
      shell: |
        /usr/local/bin/k3s-uninstall.sh || true

    # Remove Argo CD resources
    - name: Delete Argo CD namespace
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: argocd

    # Remove Longhorn resources
    - name: Delete Longhorn namespace
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: longhorn-system

    # Clean up residual files (optional)
    - name: Remove leftover K3s directories on all nodes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/rancher/k3s/
        - /etc/rancher/k3s/

