---
- name: Cluster preparation
  hosts: all
  become: true
  roles:
    - prereq
  tags:
    - preparation

- name: Setup K3s Master
  hosts: server
  become: true
  roles:
    - k3s_server
  tags:
    - k3s_setup

- name: Setup K3s Workers
  hosts: agent
  become: true
  roles:
    - k3s_agent
  tags:
    - k3s_setup

- name: Install nginx-ingress
  hosts: server
  become: true
  roles:
    - nginx-ingress
  tags:
    - nginx-ingress

- name: Install metallb
  hosts: server
  become: true
  roles:
    - metallb
  tags:
    - metallb

- name: Install cert-manager
  hosts: server
  become: true
  roles:
    - cert-manager
  tags:
    - cert-manager